[package]
name = "AdventOfCode22"
version = "0.1.0"
edition = "2021"

[lib]
name = "utilities"
path = "src/utilities.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
